-- Generated by nwg-displays on 2025-05-30 at 15:11:32, then hand-ported to Lua.

hl.monitor({ output = "DP-1", mode = "2560x1440@144.0", position = "2560x0", scale = 1.0 })
hl.monitor({ output = "DP-3", mode = "2560x1440@59.95", position = "0x0", scale = 1.0 })

-- Fallback for anything not listed above.
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- Custom reserved area:
-- hl.monitor({ output = "DP-1", reserved_area = { top = 0, bottom = 0, left = 0, right = 0 } })

-- HDMI port: mirror display. To see device names, use `hyprctl monitors`
-- hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60", position = "1920x0", scale = 1, mirror = "eDP-1" })
