# Disable blur for XWayland windows (or context menus with shadow would look weird)
windowrule = no_blur on, match:xwayland 1

# Floating
windowrule = float on, match:class ^(steam)$
windowrule = float on, match:class ^(proton)$
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(peek)$

# Tiling
windowrule = tile on, match:class ^dev\.warp\.Warp$

# Picture-in-Picture
windowrule = float on, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = keep_aspect_ratio on, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = move 73% 72%, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$ 
windowrule = size 25%, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = float on, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = pin on, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$

# Dialog windows – float+center these windows.
windowrule = center on, match:title ^(Open File)(.*)$
windowrule = center on, match:title ^(Select a File)(.*)$
windowrule = center on, match:title ^(Choose wallpaper)(.*)$
windowrule = center on, match:title ^(Open Folder)(.*)$
windowrule = center on, match:title ^(Save As)(.*)$
windowrule = center on, match:title ^(Library)(.*)$
windowrule = center on, match:title ^(File Upload)(.*)$
windowrule = float on, match:title ^(Open File)(.*)$
windowrule = float on, match:title ^(Select a File)(.*)$
windowrule = float on, match:title ^(Choose wallpaper)(.*)$
windowrule = float on, match:title ^(Open Folder)(.*)$
windowrule = float on, match:title ^(Save As)(.*)$
windowrule = float on, match:title ^(Library)(.*)$
windowrule = float on, match:title ^(File Upload)(.*)$

# steam
windowrule = immediate on, match:title .*\.exe
windowrule = immediate on, match:class ^(steam_app)

# No shadow for tiled windows (matches windows that are not floating).
windowrule = no_shadow on, float off
